$ANSIBLE_VAULT;1.1;AES256
62373461663264376437656362373133303635373332393434663036313063373039383032623661
3931303461333731346261353862623534363839343033620a623963363731393631306538663835
39313266313662653363643631376438383939343934613366653736663433663338306562613838
6665306265393830650a313737333430646530336661323736646433303632373038373362383030
39613965373236383330343564326362376163313864656666383830393764363532