# - name: Saying Hi from include
#   ansible.builtin.debug:
#     msg: "Hi from inlcude "

# - name: Saying Hi from include again
# ansible.builtin.debug:
#   msg: "Hi from inlcude but with syntax issue "

# TASK [Gathering Facts] ***************************************************************************************************************************************
# ok: [localhost]

# TASK [include-import from main.yaml] *************************************************************************************************************************
# ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
# JSON: Expecting value: line 1 column 1 (char 0)

# Syntax Error while loading YAML.
#   did not find expected '-' indicator

# The error appears to be in '/home/ec2-user/roles-ansible-roboshop/roles/common/tasks/include-import.yaml': line 6, column 1, but may
# be elsewhere in the file depending on the exact syntax problem.

# The offending line appears to be:

# - name: Saying Hi from include again
# ansible.builtin.debug:
# ^ here

- name: Saying Hi from import
  ansible.builtin.debug:
    msg: "Hi from inlcude "

- name: Saying Hi from import again
ansible.builtin.debug:
  msg: "Hi from inlcude but with syntax issue "